version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8030:80"
    volumes:
      - .:/app:delegated
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app:delegated
    env_file:
      - .env
