#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health-check:
  path: /health-check
  controller: O2O\Integration\PunkApi\Infrastructure\Controller\HealthCheckController
  methods:  [GET]
